name: ccaexplorer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  provider: ^6.0.0
  google_fonts: ^2.1.0
  firebase_core: ^1.6.0
  pinch_zoom_image_last: ^0.4.1
  full_screen_image: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  readmore: ^2.1.0
 
  firebase_storage: ^10.0.4
  image_picker: ^0.8.4+1
  url_launcher: ^6.0.10
  multi_image_picker2: ^5.0.2
  numberpicker: ^2.0.1
  syncfusion_flutter_calendar: ^19.3.45
  flutter_form_bloc: ^0.20.6
  modal_progress_hud: ^0.1.3
  list_tile_switch: ^1.0.0
  spinner_input: ^0.1.2
  url_launcher_web: ^2.0.4
  animations: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  flutter_rating_bar: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:   

  # To add assets to your application, add an assets section, like this:
  assets:   
    - assets/back_button.png
    - assets/mechchallenge.jpeg
    - assets/image2.jpg
    - assets/navigator/
    - assets/hotel/
    - assets/images/
    - assets/introduction_animation/
    - assets/event_list/
    - assets/club/
    - assets/icon/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
   




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
